# Generated by Django 4.2.2 on 2023-07-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano_referencia', models.CharField(choices=[('05/2023', 'Maio/2023'), ('06/2023', 'Junho/2023'), ('07/2023', 'Julho/2023')], max_length=20)),
                ('status', models.CharField(choices=[('anexado_nao_verificado', 'Verificado - Não Ok'), ('anexado_verificado', 'Verificado - Ok')], default='Não Verificado', max_length=30)),
                ('datetime_upload', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='estacionamento/static/comprovantes')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_id', models.IntegerField()),
                ('tipo_automovel', models.CharField(default='Automóvel', max_length=50)),
                ('frequencia', models.CharField(default='Frequência', max_length=50)),
                ('preço', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('plano', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('modelo_veiculo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga_id', models.IntegerField()),
                ('status', models.CharField(default='Vazio', max_length=20)),
                ('nome_cliente', models.CharField(default='Vazio', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaRotativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(max_length=20)),
                ('horario_entrada', models.DateTimeField()),
                ('horario_saida', models.DateTimeField()),
                ('valor_hora', models.FloatField()),
                ('tipo_automovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estacionamento.plano')),
                ('vaga_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estacionamento.vaga')),
            ],
        ),
    ]
