# Generated by Django 4.2.2 on 2023-07-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoreserva',
            name='plano',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=50),
        ),
    ]
