# Generated by Django 4.2.2 on 2023-07-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_alter_solicitacaoreserva_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
