# Generated by Django 4.2.2 on 2023-07-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0003_plano_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuvidasSugestoesReclamacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacaoreserva',
            name='plano',
            field=models.CharField(choices=[('Carro - Mensal', 'Carro - Mensal'), ('Moto - Mensal', 'Moto - Mensal')], max_length=50),
        ),
        migrations.CreateModel(
            name='ClienteMensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('modelo_veiculo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=20)),
                ('tipo_automovel', models.CharField(max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=20)),
                ('plano_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estacionamento.plano')),
                ('vaga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estacionamento.vaga')),
            ],
        ),
    ]
