# Generated by Django 4.2.2 on 2023-07-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_duvidassugestoesreclamacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvidassugestoesreclamacoes',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duvidassugestoesreclamacoes',
            name='nome_completo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
