# Generated by Django 4.2.2 on 2023-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0005_duvidassugestoesreclamacoes_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvidassugestoesreclamacoes',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
