# Generated by Django 4.2.2 on 2023-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0007_solicitacaocancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocancelamento',
            name='username',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
