# Generated by Django 4.2.3 on 2023-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0008_solicitacaocancelamento_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('nao_confirmado', 'Não Confirmado'), ('Confirmado', 'Confirmado')], default='Não Verificado', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitacaoreserva',
            name='plano',
            field=models.CharField(choices=[('Carro - Mensal R$200', 'Carro - Mensal R$200'), ('Moto Mensal R$150', 'Moto Mensal R$150')], max_length=50),
        ),
    ]
