# Generated by Django 4.2.3 on 2023-07-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0009_alter_pagamento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('Vazio', 'Vazio'), ('Reservado', 'Reservado')], default='Vazio', max_length=20),
        ),
    ]
